import '../../globals.css'

export const metadata = {
    title: 'product',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" dir='rtl' class="dark-mode">
            <body>
                <div className="w-[100vw] h-[100vh] bg-blue-500">
                {children}
                </div>
            </body>
        </html>
    )
}
